### PR TITLE
Dropdown V2 - Style Changes

### PR DESCRIPTION
**Pull request by vvunda**

### CODE REVIEW

**Review by KiranBollem — APPROVED** [review]

**Review by KiranBollem — APPROVED** [review]

**Review by travis-subaru — CHANGES_REQUESTED** [review]
Please address the following items before moving on:

1. XcodeLicenseAgreement.rtf: was this file added by accident?
2. Dropdown moves when opened. Per style guide (page 44) options should hover above dropdown (control should not move)
3. Label text (using example on login) is not visible
4. Text inside dropdown should be primary copy (style guide, page 44)
5. Highlight for selected row does not pass accessibility test (contrast is 1.51, see attached). Recommend background secondary.
6. Bounds for dropdown does not match expansion (may get fixed by fixing item 2)

Attachments:
light-mode-text-contrast
dark-mode-color-issues
wcag-tester-output

**Comment by vvunda** [comment]
why would be the Label  = Placeholder? The Label is different and placeholder is different.

**Comment by vvunda** [comment]
5. i used the color of background secondary which you recommended in the comments.

**Comment by travis-subaru** [comment]
> why would be the Label = Placeholder? The Label is different and placeholder is different.

See MyTextInput. When no placeholder is set, the label is used as a placeholder if the field has no value.

> 5\. i used the color of background secondary which you recommended in the comments.

Your change doesn't actually fix the problem. It looks like .backgroundSecondary wasn't actually applied (looks like you reverted the change).

**Comment by vvunda** [comment]
i just reverted cause the backgroundSeconmdary is not what is needed for the dark mode.

**Comment by vvunda** [comment]
Fix for the background color is pushed its due to the backgroundSecondary color on darkmode applying dark color

**Comment by vvunda** [comment]
All the comments are addressed and committed

**Pull request merged**
