### PR TITLE
Custom Dropdown component, Login screen,  Language Screen and Billing Information screen changes

### PR DESCRIPTION
**Pull request by vvunda**
- Updated the error handling for dropdown component
- The Changes of the Textinputs to dropdowns in the Billing Information screen.
- The Regions list is added to the utils function
- Fixed the errors style for the dropdown component.
- Fix for the modal background color
- Fix the close icon component

### CODE REVIEW

**Review by travis-subaru — CHANGES_REQUESTED** [review]
1. Messages: Please review [Language docs](https://github.com/travis-subaru/tb2c-mysubaru-app-v3/blob/Scripts-Cleanup/doc/language.md). In particular:
    - messages.base.json is generated from higher files and should not be edited directly.
    - messages.en_US_GIIMA.json and messages.fr_CA_MCA.json are imported from the existing apps, and should not contain new contributions
    - French (or other non-English) files should not have English values. If you cannot translate to target languages, leave these items unset.
1. Dropdown: 
    - Please fix linter issue at line 18 by adding an import.
    - As previously discussed, do not show a dimmed blue button on disabled fields. Use a diabled text field instead.
    - As previously discussed, "please select" is static text and should reflect the label of the field.
1. Billing: 
    - Per the existing app: Card number, CVV, Expiration Month and Expiration Year are cleared when editing starts. This is broken in the expiration fields by the move to dropdowns. 
    - The dropdowns have duplication wiring to different values. For example, Expiry Month contains both text={vm.cc_exp_mm} and value={expiryMonth}. These fields have two different values and will lead to bugs.
    - Dropdowns are wired with list setters like setItems={setMonths} even though there is no mechanism to change the list of months because the list of months is external to Billing Information. Why is useState being called here?
1. utils/index.js:
    - Please follow the folder / file layout used by the rest of the application. 
    - Combine getCanadaRegions / getUSARegions into a single function. The calling code shoud be able to get an appropriate list for its needs.
    - getUSARegions returns a list of abbreviations while getCanadaRegions returns full names. The style of the returns should match.
    - Per the [README](https://github.com/travis-subaru/tb2c-mysubaru-app-v3/blob/Scripts-Cleanup/README.md), please move this to TypeScript. Aside from places where TypeScript is not practical for use (like \_\_tests__), all code should be either *.ts or *.tsx.

**Review by travis-subaru — CHANGES_REQUESTED** [review]
### First Review

1. Messages: Please review [Language docs](https://github.com/travis-subaru/tb2c-mysubaru-app-v3/blob/Scripts-Cleanup/doc/language.md). In particular:
   - [x] messages.base.json is generated from higher files and should not be edited directly.
   - [X] messages.en_US_GIIMA.json and messages.fr_CA_MCA.json are imported from the existing apps, and should not contain new contributions
   - [X] French (or other non-English) files should not have English values. If you cannot translate to target languages, leave these items unset.
2. Dropdown:
   - [X] Please fix linter issue at line 18 by adding an import.
   - [ ] **See 1** As previously discussed, do not show a dimmed blue button on disabled fields. Use a disabled text field instead.
   - [X] As previously discussed, "please select" is static text and should reflect the label of the field.
3. Billing:
   - [X] Per the existing app: Card number, CVV, Expiration Month and Expiration Year are cleared when editing starts. This is broken in the expiration fields by the move to dropdowns.
   - [x] **See 3** The dropdowns have duplication wiring to different values. For example, Expiry Month contains both text={vm.cc_exp_mm} and value={expiryMonth}. These fields have two different values and will lead to bugs.
   - [ ] **See 4** Dropdowns are wired with list setters like setItems={setMonths} even though there is no mechanism to change the list of months because the list of months is external to Billing Information. Why is useState being called here?
4. utils/index.js:
   - [ ] **See 5** Please follow the folder / file layout used by the rest of the application.
   - [X] Combine getCanadaRegions / getUSARegions into a single function. The calling code shoud be able to get an appropriate list for its needs.
   - [X] getUSARegions returns a list of abbreviations while getCanadaRegions returns full names. The style of the returns should match.
   - [X] Per the [README](https://github.com/travis-subaru/tb2c-mysubaru-app-v3/blob/Scripts-Cleanup/README.md), please move this to TypeScript. Aside from places where TypeScript is not practical for use (like \_\_tests__), all code should be either *.ts or *.tsx.

### Second Review

1. MyDropdown should respect `editable` the same way MyTextInput does. This is a common property defined in react-native/TextInputProps.
2. `Expiration Year` uses `Expiration Month`'s text on the non-editable version. This appears to be a copy paste error.
3. Dropdowns still have two routes for data. For example:

    setValue={setExpiryMonth}                   
    onChangeValue={value => {
        assignVM("cc_exp_mm", value);
    }}
4. Not addressed as of commit 40a7475.
5. Not addressed as of commit 40a7475.

**Comment by vvunda** [comment]
PFA. Screenshots
LoginScreen-Notselected
LoginScreen
BillingInfo-noneditable
BillingInfo-default
BillingInfo-selected

**Comment by vvunda** [comment]
**Dark Mode** 
LoginScreen-DM
mages.githubusercontent.com/108757727/194640993-9747c141-98d1-4407-b931-57a50677d6c6.png)

**Pull request merged**
